version: '3'
services:
    postgres:
        image: 'postgres:10.5'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:4'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        user: node
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        user: node
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app
        environment:
          - WDS_SOCKET_PORT=0
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        user: node
        volumes:
            - /usr/app/node_modules
            - ./worker:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - '3050:80'